services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "{external_port}:8888/tcp"  # Dynamically assigned external port mapped to internal 8888
    volumes:
      - ./{container_name}:/gluetun  # Mount the temp directory to the /gluetun directory
    environment:
      # VPN configuration
      - VPN_SERVICE_PROVIDER=cyberghost
      - VPN_TYPE=openvpn
      
      # OpenVPN authentication
      - OPENVPN_USER=zmwdkM8gPv   # Replace with your VPN username
      - OPENVPN_PASSWORD=WUAVGBc3BM # Replace with your VPN password
      
      # Server selection
      - SERVER_COUNTRIES={country}  # Dynamically selected country

      # Other configurations
      - HTTPPROXY=on                    # Enable HTTP proxy for passing traffic through the VPN
      - TZ=Europe/Berlin                # Timezone (adjust for your location)

      # Server list updater (update every 24 hours)
      - UPDATER_PERIOD=24h
    restart: unless-stopped  # Automatically restart the container if it crashes or stops unexpectedly